using System.Collections.Generic;
using System.Threading.Tasks;

namespace OursPrivacy.Tests.Services;

public class BatchServiceTest : TestBase
{
    [Fact(Skip = "Mock server tests are disabled")]
    public async Task Create_Works()
    {
        var batch = await this.client.Batch.Create(
            new()
            {
                Token = "x",
                Events =
                [
                    new()
                    {
                        DistinctID = "x",
                        EventValue = "x",
                        DefaultProperties = new()
                        {
                            ActiveDuration = 0,
                            AdID = "ad_id",
                            AdmitadUid = "admitad_uid",
                            AdsetID = "adset_id",
                            Alart = "alart",
                            Aleid = "aleid",
                            Axwrt = "axwrt",
                            BasisCid = "basis_cid",
                            BrowserLanguage = "browser_language",
                            BrowserName = "browser_name",
                            BrowserVersion = "browser_version",
                            CampaignID = "campaign_id",
                            Clickid = "clickid",
                            Clid = "clid",
                            CpuArchitecture = "cpu_architecture",
                            CurrentUrl = "current_url",
                            Dclid = "dclid",
                            DeviceModel = "device_model",
                            DeviceType = "device_type",
                            DeviceVendor = "device_vendor",
                            Duration = 0,
                            Encoding = "encoding",
                            EngineName = "engine_name",
                            EngineVersion = "engine_version",
                            Epik = "epik",
                            Fbc = "fbc",
                            Fbclid = "fbclid",
                            Fbp = "fbp",
                            Fv = true,
                            GadSource = "gad_source",
                            Gbraid = "gbraid",
                            Gclid = "gclid",
                            Host = "host",
                            Iframe = true,
                            ImRef = "im_ref",
                            IP = "ip",
                            Irclickid = "irclickid",
                            IsBot = "is_bot",
                            LiFatID = "li_fat_id",
                            Msclkid = "msclkid",
                            Ndclid = "ndclid",
                            NewS = true,
                            OsName = "os_name",
                            OsVersion = "os_version",
                            PageHash = 0,
                            Pathname = "pathname",
                            Qclid = "qclid",
                            RdtCid = "rdt_cid",
                            ReceivedAt = "received_at",
                            Referrer = "referrer",
                            ReferringDomain = "referring_domain",
                            Sacid = "sacid",
                            Sccid = "sccid",
                            ScreenHeight = 0,
                            ScreenWidth = 0,
                            SessionCount = 0,
                            Sid = "sid",
                            Sr = "sr",
                            Title = "title",
                            Ttclid = "ttclid",
                            Twclid = "twclid",
                            Uafvl = "uafvl",
                            UserAgent = "user_agent",
                            UtmCampaign = "utm_campaign",
                            UtmContent = "utm_content",
                            UtmMedium = "utm_medium",
                            UtmName = "utm_name",
                            UtmSource = "utm_source",
                            UtmTerm = "utm_term",
                            Version = "version",
                            Wbraid = "wbraid",
                            Webview = true,
                        },
                        Email = "x",
                        EventProperties = new Dictionary<string, string?>() { { "foo", "string" } },
                        ExternalID = "x",
                        IdentityContext = new() { IP = "ip", UserAgent = "userAgent" },
                        Time = 0,
                        UserID = "x",
                        UserProperties = new()
                        {
                            AdID = "ad_id",
                            AdmitadUid = "admitad_uid",
                            AdsetID = "adset_id",
                            Alart = "alart",
                            Aleid = "aleid",
                            Axwrt = "axwrt",
                            BasisCid = "basis_cid",
                            CampaignID = "campaign_id",
                            City = "city",
                            Clickid = "clickid",
                            Clid = "clid",
                            CompanyName = "company_name",
                            Consent = new Dictionary<string, string?>() { { "foo", "string" } },
                            Country = "country",
                            CustomProperties = new Dictionary<string, string?>()
                            {
                                { "foo", "string" },
                            },
                            DateOfBirth = "date_of_birth",
                            Dclid = "dclid",
                            Email = "email",
                            Epik = "epik",
                            ExternalID = "external_id",
                            Fbc = "fbc",
                            Fbclid = "fbclid",
                            Fbp = "fbp",
                            FirstName = "first_name",
                            GadSource = "gad_source",
                            Gbraid = "gbraid",
                            Gclid = "gclid",
                            Gender = "gender",
                            ImRef = "im_ref",
                            IP = "ip",
                            Irclickid = "irclickid",
                            IsBot = "is_bot",
                            JobTitle = "job_title",
                            LastName = "last_name",
                            LiFatID = "li_fat_id",
                            Msclkid = "msclkid",
                            Ndclid = "ndclid",
                            PhoneNumber = "phone_number",
                            Qclid = "qclid",
                            RdtCid = "rdt_cid",
                            Referrer = "referrer",
                            ReferringDomain = "referring_domain",
                            Sacid = "sacid",
                            Sccid = "sccid",
                            Sid = "sid",
                            State = "state",
                            Ttclid = "ttclid",
                            Twclid = "twclid",
                            UserAgent = "user_agent",
                            UserAgentFullList = "user_agent_full_list",
                            UtmCampaign = "utm_campaign",
                            UtmContent = "utm_content",
                            UtmMedium = "utm_medium",
                            UtmName = "utm_name",
                            UtmSource = "utm_source",
                            UtmTerm = "utm_term",
                            Wbraid = "wbraid",
                            Zip = "zip",
                        },
                    },
                ],
            },
            TestContext.Current.CancellationToken
        );
        batch.Validate();
    }
}
